export const FETCH_MOVIE_BEGIN = 'FETCH_MOVIE_BEGIN'

export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS'

export const FETCH_MOVIE_FAILURE = 'FETCH_MOVIE_FAILURE'

export const FETCH_RECENT_MOVIES_BEGIN = 'FETCH_RECENT_MOVIES_BEGIN'

export const FETCH_RECENT_MOVIES_SUCCESS = 'FETCH_RECENT_MOVIES_SUCCESS'

export const FETCH_RECENT_MOVIES_FAILURE = 'FETCH_RECENT_MOVIES_FAILURE'
