export const FETCH_GENRES_BEGIN = 'FETCH_GENRES_BEGIN'

export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS'

export const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE'

export const FETCH_GENRE_MOVIES_BEGIN = 'FETCH_GENRE_MOVIES_BEGIN'

export const FETCH_GENRE_MOVIES_SUCCESS = 'FETCH_GENRE_MOVIES_SUCCESS'

export const FETCH_GENRE_MOVIES_FAILURE = 'FETCH_GENRE_MOVIES_FAILURE'

export const SET_GENRES_INDEX = 'SET_GENRES_INDEX'
